In [ ]:
import math
import numpy as np
import math
import torch

In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
import numpy.random

print(numpy.array([1,2,3]))

[1 2 3]


In [4]:
import numpy as np 
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)
b = np.array([1,2,3.1,4])
print(b.dtype) #하나라도 실수면 자동으로 실수 타입으로 된다 

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
float64


In [5]:
A = np.array([[1,2], [3,4]])
#A = np.array([[1,2,3],[1,2]])
print(A)
print(A.shape)
print(A.ndim) #차원의 수 
print(A.size) #전체 성분


[[1 2]
 [3 4]]
(2, 2)
2
4


In [11]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros(   (3,3)   ))
print(np.arange(3,10,2)) #range랑 같은데 array로 만들어준다
print(np.linspace(0,1,10, endpoint=False))


[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [18]:
A = np.array([[1,2,3], [1,2,3]])
B = np.array([[4,5,6], [1,1,1]])
C = A + B
D = A - B
print(C)
print(D)
print(A*B)
print(B**2)

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[16 25 36]
 [ 1  1  1]]


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [41]:
#행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])
print(A[-1])
print(A[:])
print(A[0][2])
print(A[0,2]) #numpy에서만 가능
B = [[1,2,3,4],[5,6,7,8]]
print(B)
print(B[0][3])
# print(B[0,2]) error가 뜬다
print(A[1,:])
print(A[1,0:3:2])
print(A[:,2])

[1 2 3]
[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
4
[4 5 6]
[4 6]
[3 6 9]


In [46]:
#boolean 인덱싱
a= [1,2,3,4,5,3,3]
print(a==3) #여러개 값 들어있는 리스트랑 3 달랑 하나랑 같느냐? 다르다
A = np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) #리스트와 달리 각각 요소에 대해 비교해준다
print(A[A==3]) #True, False가 담긴 행렬로 인덱싱이 가능하다
print(A)

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[1 2 3 4]
 [5 3 7 3]]


In [73]:
A = np.random.randn(3,3)
B = np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) #0번째 열이 0보다 작은 행

[[-0.90802965 -1.06701804 -0.88977415]
 [ 0.13489098 -0.21927518 -0.14181027]
 [ 1.40004865 -0.22312903  0.2376821 ]]
[[0.40276031 0.53597534 0.49143731]
 [0.77828502 0.60430303 0.28017654]
 [0.61451435 0.18768505 0.69012633]]
[[-0.90802965 -1.06701804 -0.88977415]]


In [95]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1)))
print(np.log10(10))
print(np.round(A))
print(np.round(A,2)) #소숫점 둘째 자리까지
print(np.floor(A)) #내림
print(np.ceil(A)) #올림

[[-0.55233707  0.35845087 -0.54000752]
 [ 0.87254815  0.68880523 -0.62563827]
 [-0.03560537  0.21333412 -0.33830162]]
[[0.55233707 0.35845087 0.54000752]
 [0.87254815 0.68880523 0.62563827]
 [0.03560537 0.21333412 0.33830162]]
[[0.74319383 0.59870767 0.73485204]
 [0.93410286 0.82994291 0.79097299]
 [0.18869385 0.46188106 0.58163702]]
[[0.57560301 1.43111073 0.58274387]
 [2.39300081 1.99133493 0.5349199 ]
 [0.96502104 1.23779815 0.71298021]]
[[-0.59359679 -1.02596366 -0.61617222]
 [-0.13633744 -0.37279673 -0.46898292]
 [-3.33525879 -1.54489571 -1.08381741]]
1.0
1.0
[[-1.  0. -1.]
 [ 1.  1. -1.]
 [-0.  0. -0.]]
[[-0.55  0.36 -0.54]
 [ 0.87  0.69 -0.63]
 [-0.04  0.21 -0.34]]
[[-1.  0. -1.]
 [ 0.  0. -1.]
 [-1.  0. -1.]]
[[-0.  1. -0.]
 [ 1.  1. -0.]
 [-0.  1. -0.]]


In [96]:
print(np.exp(-1.08))
print(np.log(np.exp(1)))

0.3395955256449391
1.0


In [ ]:
print(np.sin(np.pi/6))

0.49999999999999994


In [106]:
A = np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A, axis = 0))
print(np.max(A, axis =1))
print()
print(np.max(A, axis=0, keepdims=True))
print(np.max(A, axis=1, keepdims=True))
print(np.argmax(A))
print(np.argmax(A, axis = 0)) #각각 열에서 가장 큰 애가 존재하는 인덱스

[[ 4.52516386e-01  1.58751006e+00  1.45339011e-03 -6.80401380e-01]
 [-8.52817587e-02 -1.95167488e-01  8.89372140e-01 -6.53565954e-01]
 [ 4.10386339e-01 -8.42447462e-01  1.17622807e+00 -8.63111752e-01]]
1.5875100633766277
[ 0.45251639  1.58751006  1.17622807 -0.65356595]
[1.58751006 0.88937214 1.17622807]

[[ 0.45251639  1.58751006  1.17622807 -0.65356595]]
[[1.58751006]
 [0.88937214]
 [1.17622807]]
1
[0 0 2 1]


In [111]:
a = np.random.randn(6,1)
print(a)
a_sorted = np.sort(a, axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

[[-0.10165554]
 [ 0.18252913]
 [ 1.13874757]
 [ 1.4772679 ]
 [ 1.9364366 ]
 [-0.35133062]]
[[-0.35133062]
 [-0.10165554]
 [ 0.18252913]
 [ 1.13874757]
 [ 1.4772679 ]
 [ 1.9364366 ]]
[[ 1.9364366 ]
 [ 1.4772679 ]
 [ 1.13874757]
 [ 0.18252913]
 [-0.10165554]
 [-0.35133062]]


In [ ]:
A = np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A, axis=1))
print(np.sum(A, axis=1, keepdims=True))
print(np.mean(A))
print(np.mean(A))
print(np.mean(A, axis=1))
print(np.mean(A, axis=1, keepdims=True))
print(np.std(A)) #standard deviation

[[ 0.00436473 -0.90809393  0.21985139  0.02115352]
 [ 0.13639744 -0.91432529 -1.07780527 -0.46370094]
 [ 0.07765073 -0.74038697  2.0082051  -1.68486807]]
-3.3215575413827336
[-0.66272427 -2.31943406 -0.33939921]
[[-0.66272427]
 [-2.31943406]
 [-0.33939921]]
-0.2767964617818945
-0.2767964617818945
[-0.16568107 -0.57985851 -0.0848498 ]
[[-0.16568107]
 [-0.57985851]
 [-0.0848498 ]]
0.8949482644182805


In [135]:
A = np.random.randint(-2, 5, size = (12,))
print(A)
print(A.shape)
B = A.reshape(4,3,1) #size 개수랑 맞아야함 
print(B)
print(B.ndim)

[ 2  1  3 -2  4  1 -1 -1 -1 -2 -2  2]
(12,)
[[[ 2]
  [ 1]
  [ 3]]

 [[-2]
  [ 4]
  [ 1]]

 [[-1]
  [-1]
  [-1]]

 [[-2]
  [-2]
  [ 2]]]
3


In [153]:
a = np.array([1,2,3])
b = np.array([2,2,1])

print(np.sum(a*b))

a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A = np.random.randn(4,3,10)
print(A.transpose(0,2,1).shape) #0번째를 0번째로, 1번째를 2번째로, 2번째를 1번째로



9
[[9]]
[[9]]
(4, 10, 3)


In [ ]:
A = np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-5).shape) #4개 행이 될 수 있도록 열의 수를 마춰라 -5에는 숫자가 알아서 옴 
print(A.reshape(2,5,-1).shape)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)


In [ ]:
x = np.random.randn(2,3,4,5,6)
print (x[:,:,:,:,:].shape)
print(x)

(2, 3, 4, 5, 6)


In [180]:
A = np.random.randn(1,1,1,1,3,4,1)
#print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,6)).shape)

(1, 1, 1, 1, 3, 4, 1)
(3, 4)
(1, 1, 3, 4)


In [191]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...]
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:, np.newaxis, :]
print(A3.shape)
A1 = np.expand_dims(A1,axis=0)
print(A1.shape)
A2 = np.expand_dims(A2,axis=2)
print(A2.shape)
A3 = np.expand_dims(A3,axis=1)
print(A3.shape)


(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 1, 3, 4)
(3, 4, 1, 1)
(3, 1, 1, 4)
